### PR TITLE
Stripe Billing

### PR DESCRIPTION
**Pull request by yuchunc**
Config: 
1) `prod.exs` L:37 has an example of how to add api_key.
2) Create a produce and a corresponding plan, copy the plan's id (should start with `plan_`).
  example in `prod.exs` L:39.

### CODE REVIEW

**Comment by AlmogRnD** [comment]
what about the alerts or trail on signup? Does it lock the user out?

**Comment by yuchunc** [comment]
Do you have a user flow for this in mind?
ie. User comes to landing page -> click Sign Up to Plan -> Setup account on  Stripe -> Comes to Registration .... etc.

Also, for lock-out, we can add a plug after the team has been loaded. It can check if the team has `subscription_ended` flag, and redirect accordingly. However, since the service isn't loosing money over not locking users out at this moment, I don't think this is as urgent. Getting them to input credit card in Stripe is more critical, Magnify can probably lean on Stripe for the initial launch.

**Comment by AlmogRnD** [comment]
Hi, so for UI I see the following. Once a user is locked out there will be a button that will ask them to add the credit card, a model with some text would be good exampling the plan. The button will just trigger the Strip widget - https://stripe.com/docs/stripe-js or https://stripe-payments-demo.appspot.com/ or https://bit.ly/2kCz2Tt 

Also in the header may be some text saying free plan and upgrade button that triggers the same thing.  

In the profile view info about payment, but I can do that later. 

As for lockout, it can't be after the team is loaded because I don't think it will load that much needs to be at the root level. We don't need to check it each time but once a day

**Comment by AlmogRnD** [comment]
I don't understand why we need the card token and how I'm supposed to input that each time? Maybe I'm missing something? 

I was talking about the check if the user is paid or not, it needs to happen once they log in and if they are not paid lock them out.

**Comment by yuchunc** [comment]
Card information is submitted to stripe directly, it does not pass through backend. Once the card has been stored in Stripe, it will emit a token to represent the information.

https://stripe.com/docs/stripe-js/elements/payment-request-button#complete-payment-charges

**Comment by AlmogRnD** [comment]
Ok what about the UI and lockout checks?

**Comment by yuchunc** [comment]
I thought you are going to provide UI on your side?

Individual resource lockout checks need to be on another PR / Trello card, this feature so far has exhausted all its financial incentive.

**Comment by AlmogRnD** [comment]
@yuchunc the Trello card hard the entire break down of what needs to be done including the lockout that does not need to be a different card or pr, I want complete features.

Attached screenshot of me explaining this before you started on this 
Screen Shot 2019-09-15 at 2 09 41 PM


As for UI I'm expecting to you use the stripe widget which has UI I sent you the links for that

**Comment by yuchunc** [comment]
Despite the spec being vague, I just pushed the locks for available resources controller. 

There is no mentioned of building out the frontend stripe integration for this card, so please start another card for that. There is no way these can fit in to one day worth of work.

**Comment by AlmogRnD** [comment]
I created another card, for the Stripe UI please have a look.

**Comment by yuchunc** [comment]
Can you accept and merge this PR?

**Comment by AlmogRnD** [comment]
Not as it is will do as a final feature with the other pr

**Comment by yuchunc** [comment]
I have added a section in Team form (accessible from `:new` or `:update`), it has a stripe logo that can be click to open a Modal containing Stripe element. Once getting the token from Stripe, submitting the form will create / update application subscription.

**Pull request merged**
